/**
 * OpenClaw plugin example: KaibanJS Team with Tavily live web search (@langchain/tavily),
 * then a short brief — fast path (basic Tavily depth, two tasks).
 *
 * Requires: OPENAI_API_KEY, TAVILY_API_KEY (see README).
 */
import { TavilySearch } from '@langchain/tavily';
import { Agent, Task, Team } from 'kaibanjs';

const tavilySearch = new TavilySearch({
  maxResults: 4,
  searchDepth: 'basic',
  tavilyApiKey: process.env.TAVILY_API_KEY,
});

export const teamMetadata = {
  description:
    'KaibanJS multi-agent workflow: searches the live web with Tavily, then returns a short analysis and summary. Use for up-to-date news, “what happened today”, or any topic needing current sources (not static training data).',
  /** Drives `kaiban_run_team` parameter `inputs` — same keys as createTeam. */
  inputs: {
    type: 'object' as const,
    description:
      'Single field: topic — what to search and summarize (e.g. “latest SpaceX Starship launch”).',
    additionalProperties: false,
    properties: {
      topic: {
        type: 'string',
        description: 'Query or subject for live web search and briefing.',
      },
    },
    required: ['topic'],
  },
};

export function createTeam({
  inputs,
}: {
  inputs: Record<string, unknown>;
}): Team {
  const topic = String(inputs.topic ?? '');

  const scout = new Agent({
    name: 'Scout',
    role: 'Live Web Researcher',
    goal: 'Use Tavily to fetch fresh, real-time web results about the user topic. Prefer recent pages and cite titles/URLs.',
    background: 'Web search and source triage',
    type: 'ReactChampionAgent',
    // @ts-expect-error Tavily's Zod schema type comes from a different zod instance than KaibanJS BaseTool expects (duplicate dependency trees).
    tools: [tavilySearch],
    maxIterations: 10,
    llmConfig: {
      provider: 'openai',
      model: 'gpt-4o-mini',
    },
  });

  const briefer = new Agent({
    name: 'Brief',
    role: 'KaibanJS Briefing Analyst',
    goal: 'Turn Scout findings into a tight executive summary with clear attribution to sources.',
    background: 'Editorial summarization',
    type: 'ReactChampionAgent',
    tools: [],
    maxIterations: 6,
    llmConfig: {
      provider: 'openai',
      model: 'gpt-4o-mini',
    },
  });

  const searchTask = new Task({
    title: 'Tavily live search',
    description: `Search the web for current information about: {topic}. Use the tavily_search tool at least once with a focused query. Summarize what you found with source names and URLs.`,
    expectedOutput:
      'Bullet list of key facts with URLs from Tavily results (timestamps or “recent” when visible).',
    agent: scout,
  });

  const briefTask = new Task({
    title: 'KaibanJS brief',
    description: `Using only the prior task output, write a 4–6 sentence brief on "{topic}".`,
    expectedOutput: `A short brief ending with this exact line on its own:
--- Generated by KaibanJS (multi-agent Team) · live data via Tavily ---`,
    agent: briefer,
  });

  return new Team({
    name: 'KaibanJS Live Brief (Tavily)',
    agents: [scout, briefer],
    tasks: [searchTask, briefTask],
    inputs: { topic },
    env: {
      OPENAI_API_KEY: process.env.OPENAI_API_KEY ?? '',
      TAVILY_API_KEY: process.env.TAVILY_API_KEY ?? '',
    },
    // logLevel: 'error',
  });
}
